---
name: Call Trivy
# TEMPLATE source: https://github.com/BretFisher/github-actions-templates

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  
  scan:

    name: Scan

    permissions: read-all
      
    ### use Reusable Workflows to call my workflow remotely
    ### https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    ### you can also call workflows from inside the same repo via file path
    
    uses: mostlydevops/actions/.github/workflows/reusable-trivy-scan-image.yaml@main

    secrets:
    
      ### registry auth
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

    with:
      
      ### REQUIRED
      ### image to scan
      image: 'ghcr.io/bretfisher/github-actions-templates:latest'

      ### defaults to 0, which doesn't fail job if CVEs are found
      ### set to 1 to fail (blocking) if CVEs (of your severities) are found
      # exit-code: 0
      
      ### Comma delimited list of severities to scan for UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      ### default is HIGH,CRITICAL
      # severity: HIGH,CRITICAL

      ### Ignore unpatched/unfixed vulnerabilities
      ### defaults to true
      # ignore-unfixed: true
      
      ### Upload scan results to GitHub Security tab
      ### defaults to false
      # upload-results: false